// export const GET_USERDATA_REQUEST="GET_USERDATA_REQUEST"
// export const GET_USERDATA_SUCCESS="GET_USERDATA_SUCCESS"
// export const GET_USERDATA_FAILURE="GET_USERDATA_FAILURE"

export const GET_USERSIGNINDATA_REQUEST="GET_USERSIGNINDATA_REQUEST"
export const GET_USERSIGNINDATA_SUCCESS="GET_USERSIGNINDATA_SUCCESS"
export const GET_USERSIGNINDATA_FAILURE="GET_USERSIGNINDATA_FAILURE"